# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HtwNAI_XNTdfg2FHcMZe167eswvyIaGS
"""

import requests
from bs4 import BeautifulSoup

# Send a GET request to the website
url = "https://www.saranathan.ac.in/"
response = requests.get(url)

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(response.content, "html.parser")

# Find elements using different methods (e.g., by tag, class, or ID)
# Example 1: Find all <a> tags
links = soup.find_all("a")
for link in links:
    print(link.get("href"))

# Example 2: Find all elements with a specific CSS class
elements = soup.find_all(class_="my-class")
for element in elements:
    print(element.text)

# Example 3: Find an element by its ID
element = soup.find(id="my-id")
print(element.text)